### ISSUE TITLE
actividad 2 Infografia_ Evelyn Santiago Victoria

### ISSUE THREAD

**Issue by EvelynSantiagoVic** [SistemasTecTlaxiaco/actividad-2-infografia-EvelynSantiagoVic#1]
![infografia_ evelyn santiago victoria](https://user-images.githubusercontent.com/112225626/188254714-43b2c7e6-c302-41d7-b664-c096f174de85.jpg)

**Comment by Daisy-GonzalezLita12** [comment]
17.5

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
